name: 'replace-in-file-action'
description: 'Replaces a string in a file'
author: 'Nicholas Pate (Aspen Capital)'
inputs:
  FROM:
    required: true
    description: 'from value'
  TO:
    required: true
    description: 'to value'
  FILES:
    required: true
    description: 'files to replace'
runs:
  using: 'node12'
  main: 'dist/index.js'
